### ISSUE TITLE
Failing when run without parent id

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/dafni-model-uploader#5]
The action appears to fail when running without a parent model id. I received the below error message. After uploading via the UI and then setting a parent id, the action worked again. Full logs are here - https://github.com/OpenCLIM/coverage-calculator/runs/2493755743?check_suite_focus=true.

```Start Model ingest
Model ingest failed with status code 404 and response: 
<!doctype html>
<html lang="en">
<head>
  <title>Not Found</title>
</head>
<body>
  <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
</body>
</html>```

**Comment by tg137** [comment]
Hi Fergus,

If you upload to the latest version (1.7) this should now be fixed.
